typedef unsigned char   undefined;

typedef unsigned char    bool;
typedef unsigned char    byte;
typedef unsigned int    dword;
typedef long long    longlong;
typedef unsigned char    uchar;
typedef unsigned int    uint;
typedef unsigned long    ulong;
typedef unsigned long long    ulonglong;
typedef unsigned short    ushort;
typedef unsigned short    word;
typedef bool _Bool;

typedef enum HCI_MSG {
    HCI_ACL_DATA_RX=2054,
    HCI_CMD_STAT_EVENT=2050,
    HCI_COMMAND=2053,
    HCI_ACL_DATA_TX=2055,
    HCI_TCI_LMP=2056,
    HCI_DBG_EVT=2057,
    HCI_MSG_ID_LAST=2058,
    HCI_CMD_CMP_EVENT=2049,
    HCI_LE_EVENT=2052,
    HCI_MSG_ID_FIRST=2048,
    HCI_EVENT=2051
} HCI_MSG;

typedef uchar uint8_t;

typedef uint8_t ke_state_t;

typedef ushort uint16_t;

typedef uint16_t ke_task_id_t;

typedef uint16_t ke_msg_id_t;

typedef struct ke_state_handler ke_state_handler, *Pke_state_handler;

typedef struct ke_msg_handler ke_msg_handler, *Pke_msg_handler;

struct ke_msg_handler {
    ke_msg_id_t id;
    undefined field_0x2;
    undefined field_0x3;
    int (* func)(ke_msg_id_t, void *, ke_task_id_t, ke_task_id_t);
};

struct ke_state_handler {
    struct ke_msg_handler * msg_table;
    uint16_t msg_cnt;
    undefined field_0x6;
    undefined field_0x7;
};

typedef enum co_error {
    CO_ERROR_MEMORY_CAPA_EXCEED=7,
    CO_ERROR_INVALID_LMP_PARAM=30,
    CO_ERROR_INSTANT_PASSED=40,
    CO_ERROR_TERMINATED_MIC_FAILURE=61,
    CO_ERROR_UNSUPPORTED_LMP_PARAM_VALUE=32,
    CO_ERROR_PAIRING_WITH_UNIT_KEY_NOT_SUP=41,
    CO_ERROR_UNKNOW_ADV_ID=66,
    CO_ERROR_QOS_NOT_SUPPORTED=39,
    CO_ERROR_ROLE_SWITCH_FAIL=53,
    CO_ERROR_INSUFFICIENT_SECURITY=47,
    CO_ERROR_PIN_MISSING=6,
    CO_ERROR_LINK_KEY_CANT_CHANGE=38,
    CO_ERROR_ROLE_CHANGE_NOT_ALLOWED=33,
    CO_ERROR_CONN_ACCEPT_TIMEOUT_EXCEED=16,
    CO_ERROR_REMOTE_DEV_TERM_LOW_RESOURCES=20,
    CO_ERROR_UNSUPPORTED_REMOTE_FEATURE=26,
    CO_ERROR_DIRECT_ADV_TO=60,
    CO_ERROR_CONN_REJ_SECURITY_REASONS=14,
    CO_ERROR_ACL_CON_EXISTS=11,
    CO_ERROR_UNDEFINED=-1,
    CO_ERROR_UNKNOWN_LMP_PDU=25,
    CO_ERROR_QOS_UNACCEPTABLE_PARAM=44,
    CO_ERROR_PAIRING_NOT_ALLOWED=24,
    CO_ERROR_REMOTE_USER_TERM_CON=19,
    CO_ERROR_ROLE_SWITCH_PEND=50,
    CO_ERROR_LMP_RSP_TIMEOUT=34,
    CO_ERROR_CONN_FAILED_TO_BE_EST=62,
    CO_ERROR_SYNC_CON_LIMIT_DEV_EXCEED=10,
    CO_ERROR_REMOTE_DEV_POWER_OFF=21,
    CO_ERROR_CONN_REJ_LIMITED_RESOURCES=13,
    CO_ERROR_UNSUPPORTED=17,
    CO_ERROR_HW_MEM_ALLOC_FAIL=1,
    CO_ERROR_OP_CANCELL_BY_HOST=68,
    CO_ERROR_UNKNOWN_CONNECTION_ID=2,
    CO_ERROR_SCO_AIR_MODE_REJECTED=29,
    CO_ERROR_SP_NOT_SUPPORTED_HOST=55,
    CO_ERROR_DIFF_TRANSACTION_COLLISION=42,
    CO_ERROR_PARAM_OUT_OF_MAND_RANGE=48,
    CO_ERROR_UNKNOWN_HCI_COMMAND=1,
    CO_ERROR_CCA_REJ_USE_CLOCK_DRAG=64,
    CO_ERROR_PAGE_TIMEOUT=4,
    CO_ERROR_LMP_COLLISION=35,
    CO_ERROR_LIMIT_REACHED=67,
    CO_ERROR_HW_UART_OUT_OF_SYNC=0,
    CO_ERROR_CON_LIMIT_EXCEED=9,
    CO_ERROR_NO_ERROR=0,
    CO_ERROR_ENC_MODE_NOT_ACCEPT=37,
    CO_ERROR_QOS_REJECTED=45,
    CO_ERROR_HOST_BUSY_PAIRING=56,
    CO_ERROR_SCO_OFFSET_REJECTED=27,
    CO_ERROR_EIR_TOO_LARGE=54,
    CO_ERROR_CONTROLLER_BUSY=58,
    CO_ERROR_CON_TERM_BY_LOCAL_HOST=22,
    CO_ERROR_UNSPECIFIED_ERROR=31,
    CO_ERROR_CON_TIMEOUT=8,
    CO_ERROR_REPEATED_ATTEMPTS=23,
    CO_ERROR_UNACCEPTABLE_CONN_INT=59,
    CO_ERROR_LMP_PDU_NOT_ALLOWED=36,
    CO_ERROR_HARDWARE_FAILURE=3,
    CO_ERROR_CONN_REJ_UNACCEPTABLE_BDADDR=15,
    CO_ERROR_INVALID_HCI_PARAM=18,
    CO_ERROR_RESERVED_SLOT_VIOLATION=52,
    CO_ERROR_CHANNEL_CLASS_NOT_SUP=46,
    CO_ERROR_COMMAND_DISALLOWED=12,
    CO_ERROR_SCO_INTERVAL_REJECTED=28,
    CO_ERROR_AUTH_FAILURE=5
} co_error;

typedef ulong uint32_t;

typedef struct hci_basic_cmd_cmp_evt hci_basic_cmd_cmp_evt, *Phci_basic_cmd_cmp_evt;

struct hci_basic_cmd_cmp_evt {
    uint8_t status;
};

typedef enum hci_opcode {
    HCI_DBG_RF_REG_RD_CMD_OPCODE=-967,
    HCI_RD_LOCAL_NAME_CMD_OPCODE=3092,
    HCI_PER_INQ_MODE_CMD_OPCODE=1027,
    HCI_RD_PAGE_SCAN_ACT_CMD_OPCODE=3099,
    HCI_RD_INQ_SCAN_TYPE_CMD_OPCODE=3138,
    HCI_RD_CON_ACCEPT_TO_CMD_OPCODE=3093,
    HCI_RD_BUFF_SIZE_CMD_OPCODE=4101,
    HCI_WR_INQ_TX_PWR_LVL_CMD_OPCODE=3161,
    HCI_DBG_ER_FLASH_CMD_OPCODE=-1018,
    HCI_DBG_RF_WR_DATA_TX_CMD_OPCODE=-963,
    HCI_LE_RMV_DEV_FROM_WLST_CMD_OPCODE=8210,
    HCI_WR_SEC_CON_TEST_MODE_CMD_OPCODE=6154,
    HCI_LE_ADD_DEV_TO_WLST_CMD_OPCODE=8209,
    HCI_LE_TEST_END_CMD_OPCODE=8223,
    HCI_RD_CLK_CMD_OPCODE=5127,
    HCI_DBG_DEL_PAR_CMD_OPCODE=-1021,
    HCI_DBG_HW_REG_RD_CMD_OPCODE=-976,
    HCI_DBG_MWS_COEX_CMD_OPCODE=-955,
    HCI_WR_LINK_POL_STG_CMD_OPCODE=2061,
    HCI_WR_INQ_SCAN_ACT_CMD_OPCODE=3102,
    HCI_RD_INQ_SCAN_ACT_CMD_OPCODE=3101,
    HCI_SET_EXTERNAL_FRAME_CONFIG_CMD_OPCODE=3183,
    HCI_USER_CFM_REQ_REPLY_CMD_OPCODE=1068,
    HCI_LE_SET_EVT_MASK_CMD_OPCODE=8193,
    HCI_RD_REM_VER_INFO_CMD_OPCODE=1053,
    HCI_LE_SET_SCAN_RSP_DATA_CMD_OPCODE=8201,
    HCI_RST_FAIL_CONTACT_CNT_CMD_OPCODE=5122,
    HCI_ENH_SETUP_SYNC_CON_CMD_OPCODE=1085,
    HCI_RD_AFH_CH_ASSESS_MODE_CMD_OPCODE=3144,
    HCI_RD_EXT_INQ_RSP_CMD_OPCODE=3153,
    HCI_CREATE_NEW_UNIT_KEY_CMD_OPCODE=3083,
    HCI_HOST_NB_CMP_PKTS_CMD_OPCODE=3125,
    HCI_RD_LOOPBACK_MODE_CMD_OPCODE=6145,
    HCI_SET_RES_LT_ADDR_CMD_OPCODE=3188,
    HCI_LE_RD_SUPP_STATES_CMD_OPCODE=8220,
    HCI_DBG_RD_MEM_CMD_OPCODE=-1023,
    HCI_WR_SCAN_EN_CMD_OPCODE=3098,
    HCI_VS_AUDIO_CONFIGURE_CMD_OPCODE=-943,
    HCI_RD_TX_PWR_LVL_CMD_OPCODE=3117,
    HCI_LE_ADD_DEV_TO_RSLV_LIST_CMD_OPCODE=8231,
    HCI_WR_SYNC_FLOW_CTRL_EN_CMD_OPCODE=3119,
    HCI_LE_CREATE_CON_CMD_OPCODE=8205,
    HCI_DBG_WLAN_COEXTST_SCEN_CMD_OPCODE=-1011,
    HCI_WR_FLOW_CNTL_MODE_CMD_OPCODE=3175,
    HCI_RD_LOCAL_VER_INFO_CMD_OPCODE=4097,
    HCI_LE_ENC_CMD_OPCODE=8215,
    HCI_RD_SYNC_FLOW_CTRL_EN_CMD_OPCODE=3118,
    HCI_LE_WR_SUGGTED_DFT_DATA_LEN_CMD_OPCODE=8228,
    HCI_DBG_RD_KE_STATS_CMD_OPCODE=-1008,
    HCI_DBG_RF_CNTL_TX_CMD_OPCODE=-961,
    HCI_RD_EXT_INQ_LEN_CMD_OPCODE=3200,
    HCI_SET_CON_SLV_BCST_REC_CMD_OPCODE=1090,
    HCI_LE_SET_DATA_LEN_CMD_OPCODE=8226,
    HCI_LE_CREATE_CON_CANCEL_CMD_OPCODE=8206,
    HCI_DBG_WR_PAR_CMD_OPCODE=-1014,
    HCI_SET_CON_ENC_CMD_OPCODE=1043,
    HCI_RD_SP_MODE_CMD_OPCODE=3157,
    HCI_LE_CLEAR_WLST_CMD_OPCODE=8208,
    HCI_LE_RD_SUGGTED_DFT_DATA_LEN_CMD_OPCODE=8227,
    HCI_LE_LTK_REQ_REPLY_CMD_OPCODE=8218,
    HCI_RD_LOCAL_SUPP_CMDS_CMD_OPCODE=4098,
    HCI_SET_EVT_MASK_PAGE_2_CMD_OPCODE=3171,
    HCI_FLOW_SPEC_CMD_OPCODE=2064,
    HCI_DBG_RESET_TX_CNT_CMD_OPCODE=-968,
    HCI_REM_OOB_EXT_DATA_REQ_REPLY_CMD_OPCODE=1093,
    HCI_LE_RD_MAX_DATA_LEN_CMD_OPCODE=8239,
    HCI_DBG_RD_FLASH_CMD_OPCODE=-1016,
    HCI_DISCONNECT_CMD_OPCODE=1030,
    HCI_DBG_BLE_TST_LLCP_PT_EN_CMD_OPCODE=-958,
    HCI_RD_LOCAL_SUPP_CODECS_CMD_OPCODE=4107,
    HCI_RD_RSSI_CMD_OPCODE=5125,
    HCI_USER_PASSKEY_REQ_REPLY_CMD_OPCODE=1070,
    HCI_LE_WR_RFPATH_CPS_CMD_OPCODE=8269,
    HCI_AUTH_REQ_CMD_OPCODE=1041,
    HCI_LE_RX_TEST_CMD_OPCODE=8221,
    HCI_EXIT_PARK_STATE_CMD_OPCODE=2054,
    HCI_DBG_SET_CRC_CMD_OPCODE=-971,
    HCI_SET_MWS_TRANSPORT_LAYER_CMD_OPCODE=3185,
    HCI_EXIT_PER_INQ_MODE_CMD_OPCODE=1028,
    HCI_LE_SET_ADDR_RESOL_EN_CMD_OPCODE=8237,
    HCI_WR_LE_HOST_SUPP_CMD_OPCODE=3181,
    HCI_DBG_SET_LOCAL_CLOCK_CMD_OPCODE=-1009,
    HCI_RD_LINK_QUAL_CMD_OPCODE=5123,
    HCI_RD_PIN_TYPE_CMD_OPCODE=3081,
    HCI_DBG_WR_FLASH_CMD_OPCODE=-1017,
    HCI_DBG_WR_MEM_CMD_OPCODE=-1022,
    HCI_FLUSH_CMD_OPCODE=3080,
    HCI_VS_AUDIO_SET_MODE_CMD_OPCODE=-942,
    HCI_LE_RD_RSLV_LIST_SIZE_CMD_OPCODE=8234,
    HCI_RD_PAGE_TO_CMD_OPCODE=3095,
    HCI_WR_VOICE_STG_CMD_OPCODE=3110,
    HCI_REC_SYNC_TRAIN_CMD_OPCODE=1092,
    HCI_LE_RD_BUFF_SIZE_CMD_OPCODE=8194,
    HCI_SNIFF_MODE_CMD_OPCODE=2051,
    HCI_RD_HOLD_MODE_ACTIVITY_CMD_OPCODE=3115,
    HCI_ENH_ACCEPT_SYNC_CON_CMD_OPCODE=1086,
    HCI_RD_LINK_POL_STG_CMD_OPCODE=2060,
    HCI_SET_AFH_HOST_CH_CLASS_CMD_OPCODE=3135,
    HCI_WR_AUTO_FLUSH_TO_CMD_OPCODE=3112,
    HCI_HOST_BUF_SIZE_CMD_OPCODE=3123,
    HCI_SET_MWS_CHANNEL_PARAMS_CMD_OPCODE=3182,
    HCI_LE_RD_LOC_RSLV_ADDR_CMD_OPCODE=8236,
    HCI_DEL_RES_LT_ADDR_CMD_OPCODE=3189,
    HCI_MASTER_LK_CMD_OPCODE=1047,
    HCI_LK_REQ_REPLY_CMD_OPCODE=1035,
    HCI_WR_PAGE_TO_CMD_OPCODE=3096,
    HCI_ROLE_DISCOVERY_CMD_OPCODE=2057,
    HCI_SET_MWS_SCAN_FREQ_TABLE_CMD_OPCODE=3186,
    HCI_WR_DFT_LINK_POL_STG_CMD_OPCODE=2063,
    HCI_LE_REM_CON_PARAM_REQ_REPLY_CMD_OPCODE=8224,
    HCI_LE_CON_UPDATE_CMD_OPCODE=8211,
    HCI_LE_RD_LOC_P256_PUB_KEY_CMD_OPCODE=8229,
    HCI_DBG_RF_RD_DATA_RX_CMD_OPCODE=-962,
    HCI_WR_DFT_ERR_DATA_REP_CMD_OPCODE=3163,
    HCI_START_SYNC_TRAIN_CMD_OPCODE=1091,
    HCI_LE_LTK_REQ_NEG_REPLY_CMD_OPCODE=8219,
    HCI_QOS_SETUP_CMD_OPCODE=2055,
    HCI_LE_REM_CON_PARAM_REQ_NEG_REPLY_CMD_OPCODE=8225,
    HCI_WR_SP_DBG_MODE_CMD_OPCODE=6148,
    HCI_RD_EXT_PAGE_TO_CMD_OPCODE=3198,
    HCI_SET_CON_SLV_BCST_DATA_CMD_OPCODE=3190,
    HCI_WR_EXT_PAGE_TO_CMD_OPCODE=3199,
    HCI_DBG_RD_PAR_CMD_OPCODE=-1015,
    HCI_LE_RD_WLST_SIZE_CMD_OPCODE=8207,
    HCI_RD_CURR_IAC_LAP_CMD_OPCODE=3129,
    HCI_LE_SET_ADV_PARAM_CMD_OPCODE=8198,
    HCI_SET_MWS_SIGNALING_CMD_OPCODE=3184,
    HCI_WR_STORED_LK_CMD_OPCODE=3089,
    HCI_CHG_CON_LK_CMD_OPCODE=1045,
    HCI_WR_AUTH_EN_CMD_OPCODE=3104,
    HCI_WR_PAGE_SCAN_TYPE_CMD_OPCODE=3143,
    HCI_DBG_BLE_TST_SEND_LLCP_CMD_OPCODE=-957,
    HCI_RD_REM_EXT_FEATS_CMD_OPCODE=1052,
    HCI_LE_SET_SCAN_PARAM_CMD_OPCODE=8203,
    HCI_RESET_CMD_OPCODE=3075,
    HCI_RD_PAGE_SCAN_TYPE_CMD_OPCODE=3142,
    HCI_SET_EVT_MASK_CMD_OPCODE=3073,
    HCI_WR_EXT_INQ_RSP_CMD_OPCODE=3154,
    HCI_ENH_FLUSH_CMD_OPCODE=3167,
    HCI_WR_CLASS_OF_DEV_CMD_OPCODE=3108,
    HCI_DBG_SET_TX_PW_CMD_OPCODE=-965,
    HCI_RD_LMP_HDL_CMD_OPCODE=1056,
    HCI_LE_RD_CHNL_MAP_CMD_OPCODE=8213,
    HCI_INQ_CANCEL_CMD_OPCODE=1026,
    HCI_LK_REQ_NEG_REPLY_CMD_OPCODE=1036,
    HCI_CREATE_CON_CMD_OPCODE=1029,
    HCI_WR_AUTH_PAYL_TO_CMD_OPCODE=3196,
    HCI_REFRESH_ENC_KEY_CMD_OPCODE=3155,
    HCI_RD_FAIL_CONTACT_CNT_CMD_OPCODE=5121,
    HCI_LE_RD_PEER_RSLV_ADDR_CMD_OPCODE=8235,
    HCI_DBG_RF_SWITCH_CLK_CMD_OPCODE=-964,
    HCI_NO_OPERATION_CMD_OPCODE=0,
    HCI_RD_LOCAL_SUPP_FEATS_CMD_OPCODE=4099,
    HCI_WR_SYNC_TRAIN_PARAM_CMD_OPCODE=3192,
    HCI_SET_CON_SLV_BCST_CMD_OPCODE=1089,
    HCI_WR_CON_ACCEPT_TO_CMD_OPCODE=3094,
    HCI_RD_SCAN_EN_CMD_OPCODE=3097,
    HCI_LE_SET_ADV_EN_CMD_OPCODE=8202,
    HCI_SEND_KEYPRESS_NOTIF_CMD_OPCODE=3168,
    HCI_LE_RD_REM_USED_FEATS_CMD_OPCODE=8214,
    HCI_WR_AFH_CH_ASSESS_MODE_CMD_OPCODE=3145,
    HCI_DBG_MWS_COEXTST_SCEN_CMD_OPCODE=-954,
    HCI_REJECT_SYNC_CON_REQ_CMD_OPCODE=1066,
    HCI_IO_CAP_REQ_REPLY_CMD_OPCODE=1067,
    HCI_DBG_SET_TYPE_PUB_CMD_OPCODE=-973,
    HCI_WR_LOOPBACK_MODE_CMD_OPCODE=6146,
    HCI_DBG_RESET_RX_CNT_CMD_OPCODE=-969,
    HCI_INQ_CMD_OPCODE=1025,
    HCI_LE_RD_TRANS_PWR_CMD_OPCODE=8267,
    HCI_ACCEPT_CON_REQ_CMD_OPCODE=1033,
    HCI_PARK_STATE_CMD_OPCODE=2053,
    HCI_RD_AUTH_PAYL_TO_CMD_OPCODE=3195,
    HCI_WR_PAGE_SCAN_ACT_CMD_OPCODE=3100,
    HCI_RD_INQ_RSP_TX_PWR_LVL_CMD_OPCODE=3160,
    HCI_WR_INQ_SCAN_TYPE_CMD_OPCODE=3139,
    HCI_TRUNC_PAGE_CAN_CMD_OPCODE=1088,
    HCI_RD_AUTO_FLUSH_TO_CMD_OPCODE=3111,
    HCI_REM_OOB_DATA_REQ_REPLY_CMD_OPCODE=1072,
    HCI_EXIT_SNIFF_MODE_CMD_OPCODE=2052,
    HCI_RD_VOICE_STG_CMD_OPCODE=3109,
    HCI_RD_SEC_CON_HOST_SUPP_CMD_OPCODE=3193,
    HCI_DBG_LLCP_DISCARD_CMD_OPCODE=-970,
    HCI_DBG_WR_DLE_DFT_VALUE_CMD_OPCODE=-959,
    HCI_WR_LOCAL_NAME_CMD_OPCODE=3091,
    HCI_SET_CTRL_TO_HOST_FLOW_CTRL_CMD_OPCODE=3121,
    HCI_RD_ENC_KEY_SIZE_CMD_OPCODE=5128,
    HCI_RD_LE_HOST_SUPP_CMD_OPCODE=3180,
    HCI_WR_CURR_IAC_LAP_CMD_OPCODE=3130,
    HCI_DBG_BT_SEND_LMP_CMD_OPCODE=-1010,
    HCI_DBG_RD_MEM_INFO_CMD_OPCODE=-1006,
    HCI_DBG_SET_BD_ADDR_CMD_OPCODE=-974,
    HCI_SET_TX_PWR_CMD_OPCODE=-927,
    HCI_IO_CAP_REQ_NEG_REPLY_CMD_OPCODE=1076,
    HCI_CREATE_CON_CANCEL_CMD_OPCODE=1032,
    HCI_VS_AUDIO_SET_POINTER_CMD_OPCODE=-940,
    HCI_RD_LINK_SUPV_TO_CMD_OPCODE=3126,
    HCI_WR_INQ_MODE_CMD_OPCODE=3141,
    HCI_RD_FLOW_CNTL_MODE_CMD_OPCODE=3174,
    HCI_REM_NAME_REQ_CMD_OPCODE=1049,
    HCI_DEL_STORED_LK_CMD_OPCODE=3090,
    HCI_RD_CLASS_OF_DEV_CMD_OPCODE=3107,
    HCI_RD_NB_SUPP_IAC_CMD_OPCODE=3128,
    HCI_USER_PASSKEY_REQ_NEG_REPLY_CMD_OPCODE=1071,
    HCI_WR_SEC_CON_HOST_SUPP_CMD_OPCODE=3194,
    HCI_DBG_SET_TYPE_RAND_CMD_OPCODE=-972,
    HCI_LE_SET_HOST_CH_CLASS_CMD_OPCODE=8212,
    HCI_RD_STORED_LK_CMD_OPCODE=3085,
    HCI_USER_CFM_REQ_NEG_REPLY_CMD_OPCODE=1069,
    HCI_WR_NB_BDCST_RETX_CMD_OPCODE=3114,
    HCI_RD_INQ_MODE_CMD_OPCODE=3140,
    HCI_PIN_CODE_REQ_REPLY_CMD_OPCODE=1037,
    HCI_RD_AUTH_EN_CMD_OPCODE=3103,
    HCI_PIN_CODE_REQ_NEG_REPLY_CMD_OPCODE=1038,
    HCI_DBG_RF_SYNC_P_CNTL_CMD_OPCODE=-960,
    HCI_WR_HOLD_MODE_ACTIVITY_CMD_OPCODE=3116,
    HCI_RD_NB_BDCST_RETX_CMD_OPCODE=3113,
    HCI_REJECT_CON_REQ_CMD_OPCODE=1034,
    HCI_LE_CLEAR_RSLV_LIST_CMD_OPCODE=8233,
    HCI_DBG_RF_REG_WR_CMD_OPCODE=-966,
    HCI_RD_DFT_ERR_DATA_REP_CMD_OPCODE=3162,
    HCI_LE_SET_RAND_ADDR_CMD_OPCODE=8197,
    HCI_LE_GEN_DHKEY_CMD_OPCODE=8230,
    HCI_VS_AUDIO_GET_BUFFER_RANGE_CMD_OPCODE=-939,
    HCI_EN_DUT_MODE_CMD_OPCODE=6147,
    HCI_DBG_ID_FLASH_CMD_OPCODE=-1019,
    HCI_RD_ENH_TX_PWR_LVL_CMD_OPCODE=3176,
    HCI_WR_EXT_INQ_LEN_CMD_OPCODE=3201,
    HCI_ACCEPT_SYNC_CON_REQ_CMD_OPCODE=1065,
    HCI_RD_SYNC_TRAIN_PARAM_CMD_OPCODE=3191,
    HCI_DBG_HW_REG_WR_CMD_OPCODE=-975,
    HCI_RD_AFH_CH_MAP_CMD_OPCODE=5126,
    HCI_LE_RD_ADV_CHNL_TX_PW_CMD_OPCODE=8199,
    HCI_SETUP_SYNC_CON_CMD_OPCODE=1064,
    HCI_WR_PIN_TYPE_CMD_OPCODE=3082,
    HCI_LE_SET_RSLV_PRIV_ADDR_TO_CMD_OPCODE=8238,
    HCI_CHG_CON_PKT_TYPE_CMD_OPCODE=1039,
    HCI_RD_LOC_OOB_EXT_DATA_CMD_OPCODE=3197,
    HCI_LE_SET_ADV_DATA_CMD_OPCODE=8200,
    HCI_LE_RD_RFPATH_CPS_CMD_OPCODE=8268,
    HCI_RD_LOC_OOB_DATA_CMD_OPCODE=3159,
    HCI_SET_EVT_FILTER_CMD_OPCODE=3077,
    HCI_RD_DFT_LINK_POL_STG_CMD_OPCODE=2062,
    HCI_REM_OOB_DATA_REQ_NEG_REPLY_CMD_OPCODE=1075,
    HCI_SNIFF_SUB_CMD_OPCODE=2065,
    HCI_LE_SET_SCAN_EN_CMD_OPCODE=8204,
    HCI_WR_SP_MODE_CMD_OPCODE=3158,
    HCI_RD_REM_SUPP_FEATS_CMD_OPCODE=1051,
    HCI_RD_LOCAL_EXT_FEATS_CMD_OPCODE=4100,
    HCI_LE_RMV_DEV_FROM_RSLV_LIST_CMD_OPCODE=8232,
    HCI_SET_MWS_PATTERN_CONFIG_CMD_OPCODE=3187,
    HCI_LE_RD_LOCAL_SUPP_FEATS_CMD_OPCODE=8195,
    HCI_DBG_WLAN_COEX_CMD_OPCODE=-1013,
    HCI_GET_MWS_TRANSPORT_LAYER_CONFIG_CMD_OPCODE=5132,
    HCI_VS_AUDIO_RESET_CMD_OPCODE=-941,
    HCI_LE_START_ENC_CMD_OPCODE=8217,
    HCI_TESTER_SET_LE_PARAMS_CMD_OPCODE=-960,
    HCI_RD_CLK_OFF_CMD_OPCODE=1055,
    HCI_RD_BD_ADDR_CMD_OPCODE=4105,
    HCI_LE_RAND_CMD_OPCODE=8216,
    HCI_LE_TX_TEST_CMD_OPCODE=8222,
    HCI_DBG_PLF_RESET_CMD_OPCODE=-1007,
    HCI_WR_LINK_SUPV_TO_CMD_OPCODE=3127,
    HCI_VS_AUDIO_ALLOCATE_CMD_OPCODE=-944,
    HCI_SWITCH_ROLE_CMD_OPCODE=2059,
    HCI_HOLD_MODE_CMD_OPCODE=2049,
    HCI_REM_NAME_REQ_CANCEL_CMD_OPCODE=1050,
    HCI_TRUNC_PAGE_CMD_OPCODE=1087
} hci_opcode;

typedef struct Elf32_Shdr Elf32_Shdr, *PElf32_Shdr;

typedef enum Elf_SectionHeaderType_RISCV {
    SHT_SYMTAB=2,
    SHT_GNU_versym=1879048191,
    SHT_GNU_verdef=1879048189,
    SHT_GNU_LIBLIST=1879048183,
    SHT_FINI_ARRAY=15,
    SHT_GROUP=17,
    SHT_CHECKSUM=1879048184,
    SHT_SHLIB=10,
    SHT_ANDROID_RELA=1610612738,
    SHT_NOBITS=8,
    SHT_GNU_HASH=1879048182,
    SHT_REL=9,
    SHT_SYMTAB_SHNDX=18,
    SHT_HASH=5,
    SHT_PROGBITS=1,
    SHT_ANDROID_REL=1610612737,
    SHT_NULL=0,
    SHT_GNU_verneed=1879048190,
    SHT_INIT_ARRAY=14,
    SHT_NOTE=7,
    SHT_PREINIT_ARRAY=16,
    SHT_STRTAB=3,
    SHT_RELA=4,
    SHT_SUNW_COMDAT=1879048187,
    SHT_GNU_ATTRIBUTES=1879048181,
    SHT_DYNSYM=11,
    SHT_SUNW_syminfo=1879048188,
    SHT_DYNAMIC=6,
    SHT_SUNW_move=1879048186
} Elf_SectionHeaderType_RISCV;

struct Elf32_Shdr {
    dword sh_name;
    enum Elf_SectionHeaderType_RISCV sh_type;
    dword sh_flags;
    dword sh_addr;
    dword sh_offset;
    dword sh_size;
    dword sh_link;
    dword sh_info;
    dword sh_addralign;
    dword sh_entsize;
};

typedef struct Elf32_Rela Elf32_Rela, *PElf32_Rela;

struct Elf32_Rela {
    dword r_offset; // location to apply the relocation action
    dword r_info; // the symbol table index and the type of relocation
    dword r_addend; // a constant addend used to compute the relocatable field value
};

typedef struct Elf32_Sym Elf32_Sym, *PElf32_Sym;

struct Elf32_Sym {
    dword st_name;
    dword st_value;
    dword st_size;
    byte st_info;
    byte st_other;
    word st_shndx;
};

typedef struct Elf32_Ehdr Elf32_Ehdr, *PElf32_Ehdr;

struct Elf32_Ehdr {
    byte e_ident_magic_num;
    char e_ident_magic_str[3];
    byte e_ident_class;
    byte e_ident_data;
    byte e_ident_version;
    byte e_ident_osabi;
    byte e_ident_abiversion;
    byte e_ident_pad[7];
    word e_type;
    word e_machine;
    dword e_version;
    dword e_entry;
    dword e_phoff;
    dword e_shoff;
    dword e_flags;
    word e_ehsize;
    word e_phentsize;
    word e_phnum;
    word e_shentsize;
    word e_shnum;
    word e_shstrndx;
};




void ble_dbg_platform_reset_complete(uint32_t error)

{
  undefined *puVar1;
  
  puVar1 = (undefined *)_L0(0x801,0,0xfc11,1);
  if (error == 0xa5a5a5a5) {
    *puVar1 = 3;
  }
  else {
    if (error == 0xc3c3c3c3) {
      *puVar1 = 0;
    }
  }
  do {
                    // WARNING: Do nothing block with infinite loop
  } while( true );
}



void _L0(void)

{
  int unaff_s0;
  undefined *puVar1;
  
  puVar1 = (undefined *)_L0();
  if (unaff_s0 == -0x5a5a5a5b) {
    *puVar1 = 3;
  }
  else {
    if (unaff_s0 == -0x3c3c3c3d) {
      *puVar1 = 0;
    }
  }
  do {
                    // WARNING: Do nothing block with infinite loop
  } while( true );
}


